package MVC.View_Controller;


import MVC.Model.Mathima;
import MVC.Model.Kathigitis;
import MVC.Model.Foititis;
import MVC.Model.Account;
import MVC.Model.Admin;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author stini
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameLogin = new javax.swing.JTextField();
        passwordLogin = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        AdminPage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adminLogoutButton = new javax.swing.JButton();
        addProf = new javax.swing.JButton();
        addStd = new javax.swing.JButton();
        addMath = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        FoiththsPage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        foiththsLogoutButton = new javax.swing.JButton();
        KathigitisPage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kathigitisLogoutButton = new javax.swing.JButton();
        newStdPage = new javax.swing.JPanel();
        stdUsername = new javax.swing.JTextField();
        stdPassword = new javax.swing.JTextField();
        stdMail = new javax.swing.JTextField();
        stdOnomaEponymo = new javax.swing.JTextField();
        stdAM = new javax.swing.JTextField();
        stdTmhma = new javax.swing.JTextField();
        stdEksamino = new javax.swing.JTextField();
        stdDieythinsi = new javax.swing.JTextField();
        stdThlefwno = new javax.swing.JTextField();
        stdNewSubmit = new javax.swing.JButton();
        newProfPage = new javax.swing.JPanel();
        profOnomateponimo = new javax.swing.JTextField();
        profMail = new javax.swing.JTextField();
        profPassword = new javax.swing.JTextField();
        profUsername = new javax.swing.JTextField();
        profIdikotita = new javax.swing.JTextField();
        profTilefono = new javax.swing.JTextField();
        profTmima = new javax.swing.JTextField();
        profNewSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        profMathimata = new javax.swing.JList<>();
        newMathPage = new javax.swing.JPanel();
        mathOnoma = new javax.swing.JTextField();
        mathEksamino = new javax.swing.JTextField();
        mathTmhma = new javax.swing.JTextField();
        mathKodikos = new javax.swing.JTextField();
        mathTypos = new javax.swing.JTextField();
        mathNewSubmit = new javax.swing.JButton();
        mathDM = new javax.swing.JTextField();
        searchStdPage = new javax.swing.JPanel();
        searchStdUsername = new javax.swing.JTextField();
        searchStdButton = new javax.swing.JButton();
        updateStdPage = new javax.swing.JPanel();
        updateStdUsername = new javax.swing.JTextField();
        updateStdOnomatep = new javax.swing.JTextField();
        updateStdTilefono = new javax.swing.JTextField();
        updateStdAM = new javax.swing.JTextField();
        updateStdTmima = new javax.swing.JTextField();
        updateStdExamino = new javax.swing.JTextField();
        updateStdDieuthinsi = new javax.swing.JTextField();
        updateStdPassword = new javax.swing.JTextField();
        updateStdMail = new javax.swing.JTextField();
        updateStdButton = new javax.swing.JToggleButton();
        deleteStdButton = new javax.swing.JToggleButton();
        updateMathPage = new javax.swing.JPanel();
        updateMathOnoma = new javax.swing.JTextField();
        updateMathExamino = new javax.swing.JTextField();
        updateMathKodikos = new javax.swing.JTextField();
        updateMathTmima = new javax.swing.JTextField();
        updateMathTupos = new javax.swing.JTextField();
        updateMathDM = new javax.swing.JTextField();
        deleteMathButton = new javax.swing.JButton();
        updateMathButton = new javax.swing.JToggleButton();
        searchMathPage = new javax.swing.JPanel();
        searchMathKodikos = new javax.swing.JTextField();
        searchMathButton = new javax.swing.JButton();
        searchProfPage = new javax.swing.JPanel();
        searchProfUsername = new javax.swing.JTextField();
        searchProfButton = new javax.swing.JButton();
        updateProfPage = new javax.swing.JPanel();
        updateProfMail = new javax.swing.JTextField();
        updateProfPassword = new javax.swing.JTextField();
        updateProfTilefono = new javax.swing.JTextField();
        updateProfOnomatep = new javax.swing.JTextField();
        updateProfUsername = new javax.swing.JTextField();
        updateProfTmima = new javax.swing.JTextField();
        updateProfEidikothta = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        updateProfMathimata = new javax.swing.JList<>();
        updateProfButton = new javax.swing.JToggleButton();
        deleteProfButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(usernameLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(passwordLogin)))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(usernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButton)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        jLabel1.setText("Admin Page");

        adminLogoutButton.setText("LogOut");
        adminLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLogoutButtonActionPerformed(evt);
            }
        });

        addProf.setText("Add Professor");
        addProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProfActionPerformed(evt);
            }
        });

        addStd.setText("Add Student");
        addStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStdActionPerformed(evt);
            }
        });

        addMath.setText("Add Course");
        addMath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMathActionPerformed(evt);
            }
        });

        jButton5.setText("Update Student");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setText("Update Mathima");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Update Professor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminPageLayout = new javax.swing.GroupLayout(AdminPage);
        AdminPage.setLayout(AdminPageLayout);
        AdminPageLayout.setHorizontalGroup(
            AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPageLayout.createSequentialGroup()
                .addGroup(AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPageLayout.createSequentialGroup()
                        .addContainerGap(519, Short.MAX_VALUE)
                        .addComponent(adminLogoutButton))
                    .addGroup(AdminPageLayout.createSequentialGroup()
                        .addGroup(AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AdminPageLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AdminPageLayout.createSequentialGroup()
                                    .addGap(136, 136, 136)
                                    .addComponent(addProf))
                                .addGroup(AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addMath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addStd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                            .addGroup(AdminPageLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton5)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AdminPageLayout.setVerticalGroup(
            AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(addProf)
                .addGap(28, 28, 28)
                .addComponent(addStd)
                .addGap(18, 18, 18)
                .addComponent(addMath)
                .addGap(28, 28, 28)
                .addComponent(jButton5)
                .addGap(33, 33, 33)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(adminLogoutButton)
                .addContainerGap())
        );

        getContentPane().add(AdminPage, "card3");

        jLabel2.setText("Φοιτητής ");

        foiththsLogoutButton.setText("LogOut");
        foiththsLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foiththsLogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FoiththsPageLayout = new javax.swing.GroupLayout(FoiththsPage);
        FoiththsPage.setLayout(FoiththsPageLayout);
        FoiththsPageLayout.setHorizontalGroup(
            FoiththsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FoiththsPageLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel2)
                .addContainerGap(394, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FoiththsPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(foiththsLogoutButton)
                .addContainerGap())
        );
        FoiththsPageLayout.setVerticalGroup(
            FoiththsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FoiththsPageLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 354, Short.MAX_VALUE)
                .addComponent(foiththsLogoutButton)
                .addContainerGap())
        );

        getContentPane().add(FoiththsPage, "card4");

        jLabel3.setText("Καθηγητής");

        kathigitisLogoutButton.setText("LogOut");
        kathigitisLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kathigitisLogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KathigitisPageLayout = new javax.swing.GroupLayout(KathigitisPage);
        KathigitisPage.setLayout(KathigitisPageLayout);
        KathigitisPageLayout.setHorizontalGroup(
            KathigitisPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KathigitisPageLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel3)
                .addContainerGap(406, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KathigitisPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kathigitisLogoutButton)
                .addContainerGap())
        );
        KathigitisPageLayout.setVerticalGroup(
            KathigitisPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KathigitisPageLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(kathigitisLogoutButton)
                .addContainerGap())
        );

        getContentPane().add(KathigitisPage, "card5");

        stdUsername.setText("jTextField2");

        stdPassword.setText("jTextField3");

        stdMail.setText("jTextField4");

        stdOnomaEponymo.setText("jTextField4");

        stdAM.setText("jTextField4");

        stdTmhma.setText("jTextField4");

        stdEksamino.setText("jTextField4");

        stdDieythinsi.setText("jTextField4");

        stdThlefwno.setText("jTextField4");

        stdNewSubmit.setText("Submit");
        stdNewSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdNewSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newStdPageLayout = new javax.swing.GroupLayout(newStdPage);
        newStdPage.setLayout(newStdPageLayout);
        newStdPageLayout.setHorizontalGroup(
            newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStdPageLayout.createSequentialGroup()
                .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(newStdPageLayout.createSequentialGroup()
                        .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newStdPageLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(stdUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStdPageLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stdAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdEksamino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdThlefwno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(258, 258, 258)))
                        .addComponent(stdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newStdPageLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(stdMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stdOnomaEponymo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newStdPageLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stdDieythinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdTmhma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStdPageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(stdNewSubmit)
                .addGap(34, 34, 34))
        );
        newStdPageLayout.setVerticalGroup(
            newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newStdPageLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdOnomaEponymo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(stdThlefwno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdTmhma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newStdPageLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(stdDieythinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newStdPageLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(stdEksamino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stdNewSubmit)
                .addGap(36, 36, 36))
        );

        getContentPane().add(newStdPage, "card6");

        profOnomateponimo.setText("jTextField4");

        profMail.setText("jTextField4");

        profPassword.setText("jTextField3");

        profUsername.setText("jTextField2");

        profIdikotita.setText("jTextField4");

        profTilefono.setText("jTextField4");

        profTmima.setText("jTextField4");

        profNewSubmit.setText("Submit");
        profNewSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profNewSubmitActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(profMathimata);

        javax.swing.GroupLayout newProfPageLayout = new javax.swing.GroupLayout(newProfPage);
        newProfPage.setLayout(newProfPageLayout);
        newProfPageLayout.setHorizontalGroup(
            newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProfPageLayout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newProfPageLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(profNewSubmit)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newProfPageLayout.createSequentialGroup()
                        .addComponent(profIdikotita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
            .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newProfPageLayout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(newProfPageLayout.createSequentialGroup()
                            .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(newProfPageLayout.createSequentialGroup()
                                    .addComponent(profUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newProfPageLayout.createSequentialGroup()
                                    .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(profTilefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(profTmima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(258, 258, 258)))
                            .addComponent(profPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(newProfPageLayout.createSequentialGroup()
                            .addComponent(profMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profOnomateponimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(108, 108, 108)))
        );
        newProfPageLayout.setVerticalGroup(
            newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newProfPageLayout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(profIdikotita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profNewSubmit))
                .addContainerGap())
            .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newProfPageLayout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(profUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(profMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profOnomateponimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(178, 178, 178)
                    .addComponent(profTilefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(60, 60, 60)
                    .addComponent(profTmima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(newProfPage, "card7");

        mathOnoma.setText("Onoma Mathimatos");

        mathEksamino.setText("eksamino");

        mathTmhma.setText("tmhmaMathimatos");

        mathKodikos.setText("kodikosMathimatos");

        mathTypos.setText("typosMathimatos");

        mathNewSubmit.setText("Submit");
        mathNewSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathNewSubmitActionPerformed(evt);
            }
        });

        mathDM.setText("didaktikesMonades");

        javax.swing.GroupLayout newMathPageLayout = new javax.swing.GroupLayout(newMathPage);
        newMathPage.setLayout(newMathPageLayout);
        newMathPageLayout.setHorizontalGroup(
            newMathPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newMathPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mathNewSubmit)
                .addGap(39, 39, 39))
            .addGroup(newMathPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newMathPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mathOnoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mathEksamino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(newMathPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(mathTypos, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mathTmhma, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mathKodikos, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(mathDM, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(479, Short.MAX_VALUE))
        );
        newMathPageLayout.setVerticalGroup(
            newMathPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newMathPageLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(mathOnoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mathEksamino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mathTmhma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mathKodikos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mathTypos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mathDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(mathNewSubmit)
                .addGap(27, 27, 27))
        );

        getContentPane().add(newMathPage, "card8");

        searchStdUsername.setText("Username");

        searchStdButton.setText("Search");
        searchStdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStdButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchStdPageLayout = new javax.swing.GroupLayout(searchStdPage);
        searchStdPage.setLayout(searchStdPageLayout);
        searchStdPageLayout.setHorizontalGroup(
            searchStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchStdPageLayout.createSequentialGroup()
                .addContainerGap(431, Short.MAX_VALUE)
                .addGroup(searchStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchStdPageLayout.createSequentialGroup()
                        .addComponent(searchStdButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchStdPageLayout.createSequentialGroup()
                        .addComponent(searchStdUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );
        searchStdPageLayout.setVerticalGroup(
            searchStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchStdPageLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(searchStdUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 398, Short.MAX_VALUE)
                .addComponent(searchStdButton)
                .addContainerGap())
        );

        getContentPane().add(searchStdPage, "card12");

        updateStdUsername.setText("Username");

        updateStdOnomatep.setText("Onomateponimo");

        updateStdTilefono.setText("Tilefono");

        updateStdAM.setText("AM");

        updateStdTmima.setText("Tmima");

        updateStdExamino.setText("Examino");

        updateStdDieuthinsi.setText("Dieuthinsi");

        updateStdPassword.setText("Password");

        updateStdMail.setText("Mail");

        updateStdButton.setText("Update");
        updateStdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStdButtonActionPerformed(evt);
            }
        });

        deleteStdButton.setText("Delete");
        deleteStdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStdButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateStdPageLayout = new javax.swing.GroupLayout(updateStdPage);
        updateStdPage.setLayout(updateStdPageLayout);
        updateStdPageLayout.setHorizontalGroup(
            updateStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateStdPageLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(updateStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateStdPassword)
                    .addComponent(updateStdMail, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(updateStdDieuthinsi)
                    .addComponent(updateStdOnomatep)
                    .addComponent(updateStdTilefono)
                    .addComponent(updateStdAM)
                    .addComponent(updateStdTmima)
                    .addComponent(updateStdExamino, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(updateStdUsername))
                .addContainerGap(453, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateStdPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteStdButton)
                .addContainerGap())
            .addGroup(updateStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(updateStdPageLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(updateStdButton)
                    .addContainerGap(519, Short.MAX_VALUE)))
        );
        updateStdPageLayout.setVerticalGroup(
            updateStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateStdPageLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(updateStdUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateStdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateStdMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateStdOnomatep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateStdTilefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateStdAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateStdTmima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateStdExamino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateStdDieuthinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(deleteStdButton)
                .addContainerGap())
            .addGroup(updateStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(updateStdPageLayout.createSequentialGroup()
                    .addContainerGap(438, Short.MAX_VALUE)
                    .addComponent(updateStdButton)
                    .addContainerGap()))
        );

        getContentPane().add(updateStdPage, "card13");

        updateMathOnoma.setText("Onoma");

        updateMathExamino.setText("Examino");

        updateMathKodikos.setText("Kodikos");

        updateMathTmima.setText("Tmima");

        updateMathTupos.setText("Tupos");

        updateMathDM.setText("Didaktikes monades");

        deleteMathButton.setText("Delete");
        deleteMathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMathButtonActionPerformed(evt);
            }
        });

        updateMathButton.setText("Update");
        updateMathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMathButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateMathPageLayout = new javax.swing.GroupLayout(updateMathPage);
        updateMathPage.setLayout(updateMathPageLayout);
        updateMathPageLayout.setHorizontalGroup(
            updateMathPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateMathPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateMathPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateMathPageLayout.createSequentialGroup()
                        .addComponent(updateMathButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 446, Short.MAX_VALUE)
                        .addComponent(deleteMathButton))
                    .addGroup(updateMathPageLayout.createSequentialGroup()
                        .addGroup(updateMathPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateMathDM, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(updateMathTupos)
                            .addComponent(updateMathTmima)
                            .addComponent(updateMathKodikos)
                            .addComponent(updateMathExamino)
                            .addComponent(updateMathOnoma))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        updateMathPageLayout.setVerticalGroup(
            updateMathPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateMathPageLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(updateMathOnoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateMathExamino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateMathKodikos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateMathTmima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateMathTupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateMathDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(updateMathPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteMathButton)
                    .addComponent(updateMathButton))
                .addContainerGap())
        );

        getContentPane().add(updateMathPage, "card11");

        searchMathKodikos.setText("Kodikos Mathimatos");

        searchMathButton.setText("Search");
        searchMathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMathButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchMathPageLayout = new javax.swing.GroupLayout(searchMathPage);
        searchMathPage.setLayout(searchMathPageLayout);
        searchMathPageLayout.setHorizontalGroup(
            searchMathPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchMathPageLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(searchMathKodikos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(401, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchMathPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchMathButton)
                .addContainerGap())
        );
        searchMathPageLayout.setVerticalGroup(
            searchMathPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchMathPageLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(searchMathKodikos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                .addComponent(searchMathButton)
                .addContainerGap())
        );

        getContentPane().add(searchMathPage, "card12");

        searchProfUsername.setText("Kodikos Mathimatos");

        searchProfButton.setText("Search");
        searchProfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProfButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchProfPageLayout = new javax.swing.GroupLayout(searchProfPage);
        searchProfPage.setLayout(searchProfPageLayout);
        searchProfPageLayout.setHorizontalGroup(
            searchProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchProfPageLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(searchProfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(401, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchProfPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchProfButton)
                .addContainerGap())
        );
        searchProfPageLayout.setVerticalGroup(
            searchProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchProfPageLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(searchProfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                .addComponent(searchProfButton)
                .addContainerGap())
        );

        getContentPane().add(searchProfPage, "card13");

        updateProfMail.setText("Mail");

        updateProfPassword.setText("Password");

        updateProfTilefono.setText("Tilefono");

        updateProfOnomatep.setText("Onomateponimo");

        updateProfUsername.setText("Username");

        updateProfTmima.setText("Tmima");

        updateProfEidikothta.setText("Eidikothta");

        jScrollPane2.setViewportView(updateProfMathimata);

        updateProfButton.setText("Update");
        updateProfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfButtonActionPerformed(evt);
            }
        });

        deleteProfButton.setText("Delete");
        deleteProfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProfButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateProfPageLayout = new javax.swing.GroupLayout(updateProfPage);
        updateProfPage.setLayout(updateProfPageLayout);
        updateProfPageLayout.setHorizontalGroup(
            updateProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateProfPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateProfButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteProfButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateProfPageLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(updateProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateProfPassword)
                    .addComponent(updateProfMail)
                    .addComponent(updateProfOnomatep)
                    .addComponent(updateProfTilefono)
                    .addComponent(updateProfTmima)
                    .addComponent(updateProfEidikothta)
                    .addComponent(updateProfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        updateProfPageLayout.setVerticalGroup(
            updateProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateProfPageLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(updateProfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateProfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateProfMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateProfOnomatep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateProfTilefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(updateProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateProfPageLayout.createSequentialGroup()
                        .addComponent(updateProfTmima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateProfEidikothta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(updateProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateProfButton)
                    .addComponent(deleteProfButton))
                .addContainerGap())
        );

        getContentPane().add(updateProfPage, "card14");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        FileInputStream fi=null;
        ObjectInputStream oi=null;
        try {
            fi = new FileInputStream(new File("myAccounts.txt"));
            oi = new ObjectInputStream(fi);
            Account a1;
            String usernameTextfield = usernameLogin.getText();
            char[] passwordTextfield = passwordLogin.getPassword();
            
            while (true){
                try{
                    a1=(Account)oi.readObject();
                    if(a1 instanceof Admin){
                        admin = (Admin)a1;
                    }
                    char[] passwordArray = a1.getPassword().toCharArray();
                    if(Arrays.equals(passwordTextfield, passwordArray) && a1.getUsername().equals(usernameTextfield)){
                        getContentPane().removeAll();
                        getContentPane().repaint();
                        getContentPane().revalidate();
                        switch (a1.getIdiotita()) {
                            case "Administrator":
                                getContentPane().add(AdminPage);
                                break;
                            case "Professor":
                                getContentPane().add(KathigitisPage);
                                break;
                            case "Student":
                                getContentPane().add(FoiththsPage);
                                break;
                            default:
                                break;
                        }
                        getContentPane().repaint();
                        getContentPane().revalidate();
                        break;
                    }
                }catch (EOFException ex1) {
                    break; //EOF reached.
                }catch (IOException ex2) {
                    resetAccountFile();
                    JOptionPane.showMessageDialog(null, "File was reset");
                    loginButtonActionPerformed(evt);
                    break;
                }catch (ClassNotFoundException ex) {
                    System.out.println("Ex1");
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (IOException ex) {
            resetAccountFile();
            JOptionPane.showMessageDialog(null, "Someone changed or removed the file manually, File is resetting! Sign in as an admin");
        }finally{
            try{
                oi.close();
                fi.close();
                System.out.println("ekleisa");
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            clearLoginFields();
        }
        
    }//GEN-LAST:event_loginButtonActionPerformed

    public void resetAccountFile(){
        Account admin = new Admin("admin", "admin", "admin@it.teithe.gr", "Γιώργος Στίνης", "2310555555");
        try{
            f = new FileOutputStream(new File("myAccounts.txt"));
            o = new ObjectOutputStream(f);
            o.writeObject(admin);
            o.close();
            f.close();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void kathigitisLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kathigitisLogoutButtonActionPerformed
        goToHomePage();
    }//GEN-LAST:event_kathigitisLogoutButtonActionPerformed

    private void foiththsLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foiththsLogoutButtonActionPerformed
        goToHomePage();
    }//GEN-LAST:event_foiththsLogoutButtonActionPerformed

    private void adminLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLogoutButtonActionPerformed
        goToHomePage();
    }//GEN-LAST:event_adminLogoutButtonActionPerformed

    private void addStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStdActionPerformed
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        getContentPane().add(newStdPage);
        getContentPane().repaint();
        getContentPane().revalidate();
    }//GEN-LAST:event_addStdActionPerformed

    private void stdNewSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdNewSubmitActionPerformed
        String usernameStd = stdUsername.getText();
        String passStd = stdPassword.getText();
        String mailStd = stdMail.getText();
        String onomateponumoStd = stdOnomaEponymo.getText();
        String thlefwnoStd = stdThlefwno.getText();
        int AMstd = Integer.parseInt(stdAM.getText());
        String tmhmaStd = stdTmhma.getText();
        int eksaminoStd = Integer.parseInt(stdEksamino.getText());
        String dieythinsiStd = stdDieythinsi.getText();
        admin.createStd(usernameStd, passStd, mailStd, onomateponumoStd, thlefwnoStd, AMstd, tmhmaStd, eksaminoStd, dieythinsiStd);
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        getContentPane().add(AdminPage);
        getContentPane().repaint();
        getContentPane().revalidate();
    }//GEN-LAST:event_stdNewSubmitActionPerformed

    private void profNewSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profNewSubmitActionPerformed
        int[] selectedIx = profMathimata.getSelectedIndices();
        FileInputStream fi = null;
        ObjectInputStream oi = null;
        List<Mathima> mathimata = new ArrayList<>();
        try{
            fi = new FileInputStream(new File("myCourses.txt"));
            oi = new ObjectInputStream(fi);
            while (true){
                try{
                    mathimata.add((Mathima)oi.readObject());
                }catch (EOFException ex1) {
                    break; //EOF reached.
                }catch (IOException ex2) {
                    System.err.println("An IOException was caught: " + ex2.getMessage());
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try{
                oi.close();
                fi.close();
                System.out.println("ekleisa");
            }catch(IOException ex) {
                System.err.println("An IOException was caught: " + ex.getMessage());
            }
        }
        List<Mathima> mathimataForProf = new ArrayList<>();
        for (int i : selectedIx){
            String math = profMathimata.getModel().getElementAt(i);
            for (Mathima mathima : mathimata){
                if (math.equals(mathima.getOnomaMathimatos())){
                    mathimataForProf.add(mathima);
                }
            }            
        }
        
        String usernameProf = profUsername.getText();
        String passWordProf = profPassword.getText();
        String mailProf = profMail.getText();
        String onomateponumoProf = profOnomateponimo.getText();
        String thlefwnoProf = profTilefono.getText();
        String idikotitaProf = profIdikotita.getText();
        String tmimaProf = profTmima.getText();
        admin.createProf(usernameProf, passWordProf, mailProf, onomateponumoProf, thlefwnoProf, idikotitaProf, tmimaProf, mathimataForProf);
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        getContentPane().add(AdminPage);
        getContentPane().repaint();
        getContentPane().revalidate();
    }//GEN-LAST:event_profNewSubmitActionPerformed

    private void addProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProfActionPerformed
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        FileInputStream fi = null;
        ObjectInputStream oi = null;
        List<Mathima> mathimata = new ArrayList<>();
        try{
            fi = new FileInputStream(new File("myCourses.txt"));
            oi = new ObjectInputStream(fi);
            while (true){
                try{
                    mathimata.add((Mathima)oi.readObject());
                }catch (EOFException ex1) {
                    break; //EOF reached.
                }catch (IOException ex2) {
                    System.err.println("An IOException was caught: " + ex2.getMessage());
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try{
                oi.close();
                fi.close();
                System.out.println("ekleisa");
            }catch(IOException ex) {
                System.err.println("An IOException was caught: " + ex.getMessage());
            }
        }
        DefaultListModel listModel = new DefaultListModel();
        for (Mathima mathima : mathimata) {
            listModel.addElement(mathima.getOnomaMathimatos());
        }
        profMathimata.setModel(listModel);
        getContentPane().add(newProfPage);
        getContentPane().repaint();
        getContentPane().revalidate();
    }//GEN-LAST:event_addProfActionPerformed

    private void mathNewSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathNewSubmitActionPerformed
        String onomaMath = mathOnoma.getText();
        int eksamhnoMath = Integer.parseInt(mathEksamino.getText());
        String tmhmaMath = mathTmhma.getText();
        int kodikosMath = Integer.parseInt(mathKodikos.getText());
        String typosMath = mathTypos.getText();
        int dmMath = Integer.parseInt(mathDM.getText());
        admin.createCourse(onomaMath, eksamhnoMath, tmhmaMath, kodikosMath, typosMath, dmMath);
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        getContentPane().add(AdminPage);
        getContentPane().repaint();
        getContentPane().revalidate();
    }//GEN-LAST:event_mathNewSubmitActionPerformed

    private void addMathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMathActionPerformed
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        getContentPane().add(newMathPage);
        getContentPane().repaint();
        getContentPane().revalidate();
    }//GEN-LAST:event_addMathActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        getContentPane().add(searchStdPage);
        getContentPane().repaint();
        getContentPane().revalidate();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void searchStdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStdButtonActionPerformed
        String username = searchStdUsername.getText();
        std = admin.searchStd(username);
        if (std != null){
            getContentPane().removeAll();
            getContentPane().repaint();
            getContentPane().revalidate();
            getContentPane().add(updateStdPage);
            getContentPane().repaint();
            getContentPane().revalidate();
            updateStdUsername.setText(username);
            updateStdPassword.setText(std.getPassword());
            updateStdMail.setText(std.getMail());
            updateStdOnomatep.setText(std.getOnomateponumo());
            updateStdTilefono.setText(std.getTilefwno());
            updateStdAM.setText(String.valueOf(std.getAM()));
            updateStdTmima.setText(std.getTmima());
            updateStdExamino.setText(String.valueOf(std.getEksamino()));
            updateStdDieuthinsi.setText(std.getDieuthinsi());
        }
    }//GEN-LAST:event_searchStdButtonActionPerformed

    private void updateStdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStdButtonActionPerformed
        admin.updateStd(updateStdUsername.getText(), updateStdPassword.getText(),updateStdMail.getText(),updateStdMail.getText(),
                         updateStdTilefono.getText(), Integer.parseInt(updateStdAM.getText()),updateStdTmima.getText(),
                         Integer.parseInt(updateStdExamino.getText()),updateStdDieuthinsi.getText());
    }//GEN-LAST:event_updateStdButtonActionPerformed

    private void deleteStdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStdButtonActionPerformed
        admin.deleteStd();
    }//GEN-LAST:event_deleteStdButtonActionPerformed

    private void searchMathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMathButtonActionPerformed
        
        int kodikos = Integer.parseInt(searchMathKodikos.getText());
        math = admin.searchMath(kodikos);
        if (math != null){
            getContentPane().removeAll();
            getContentPane().repaint();
            getContentPane().revalidate();
            getContentPane().add(updateMathPage);
            getContentPane().repaint();
            getContentPane().revalidate();
            updateMathOnoma.setText(math.getOnomaMathimatos());
            updateMathExamino.setText(String.valueOf(math.getEksamino()));
            updateMathKodikos.setText(String.valueOf(math.getKodikosMathimatos()));
            updateMathTmima.setText(math.getTmhmaMathimatos());
            updateMathTupos.setText(math.getTyposMathimatos());
            updateMathDM.setText(String.valueOf(math.getDidaktikesMonades()));
            
        } 
        
        
    }//GEN-LAST:event_searchMathButtonActionPerformed

    private void deleteMathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMathButtonActionPerformed
        admin.deleteCourse();        
    }//GEN-LAST:event_deleteMathButtonActionPerformed

    private void updateMathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMathButtonActionPerformed
        admin.updateMath(updateMathOnoma.getText(), Integer.parseInt(updateMathExamino.getText()),updateMathTmima.getText(),Integer.parseInt(updateMathKodikos.getText()),
                         updateMathTupos.getText(), Integer.parseInt(updateMathDM.getText()));
        
    }//GEN-LAST:event_updateMathButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        getContentPane().add(searchMathPage);
        getContentPane().repaint();
        getContentPane().revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchProfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProfButtonActionPerformed
        String username = searchProfUsername.getText();
        prof = admin.searchProf(username);
        if (prof != null){
            getContentPane().removeAll();
            getContentPane().repaint();
            getContentPane().revalidate();
            getContentPane().add(updateProfPage);
            getContentPane().repaint();
            getContentPane().revalidate();
            updateProfUsername.setText(username);
            updateProfPassword.setText(prof.getPassword());
            updateProfMail.setText(prof.getMail());
            updateProfOnomatep.setText(prof.getOnomateponumo());
            updateProfTilefono.setText(prof.getTilefwno());
            updateProfTmima.setText(prof.getTmima());
            updateProfEidikothta.setText(String.valueOf(prof.getEidikotita()));
            FileInputStream fi = null;
            ObjectInputStream oi = null;
            List<Mathima> mathimata = new ArrayList<>();
            try{
                fi = new FileInputStream(new File("myCourses.txt"));
                oi = new ObjectInputStream(fi);
                while (true){
                    try{
                        mathimata.add((Mathima)oi.readObject());
                    }catch (EOFException ex1) {
                        break; //EOF reached.
                    }catch (IOException ex2) {
                        System.err.println("An IOException was caught: " + ex2.getMessage());
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try{
                    oi.close();
                    fi.close();
                    System.out.println("ekleisa");
                }catch(IOException ex) {
                    System.err.println("An IOException was caught: " + ex.getMessage());
                }
            }
            DefaultListModel listModel = new DefaultListModel();
            List<Mathima> mathimataProf = new ArrayList<>();
            mathimataProf = prof.getMathimata();
            for (Mathima mathima : mathimata) {
                listModel.addElement(mathima.getOnomaMathimatos());
            }
            updateProfMathimata.setModel(listModel);
            int[] selectedIndices = new int[mathimataProf.size()];
            for (int i = 0; i < mathimataProf.size(); i++){
                for (int k = 0; k < updateProfMathimata.getModel().getSize(); k++){
                    System.out.println(updateProfMathimata.getModel().getElementAt(k)+"\n");
                    System.out.println(mathimataProf.get(i).getOnomaMathimatos());
                    if (mathimataProf.get(i).getOnomaMathimatos().equals(updateProfMathimata.getModel().getElementAt(k)))
                        selectedIndices[i] = k;
                }
            }
            updateProfMathimata.setSelectedIndices(selectedIndices);
        }
    }//GEN-LAST:event_searchProfButtonActionPerformed

    private void updateProfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfButtonActionPerformed
        int[] selectedIx = updateProfMathimata.getSelectedIndices();
        FileInputStream fi = null;
        ObjectInputStream oi = null;
        List<Mathima> mathimata = new ArrayList<>();
        try{
            fi = new FileInputStream(new File("myCourses.txt"));
            oi = new ObjectInputStream(fi);
            while (true){
                try{
                    mathimata.add((Mathima)oi.readObject());
                }catch (EOFException ex1) {
                    break; //EOF reached.
                }catch (IOException ex2) {
                    System.err.println("An IOException was caught: " + ex2.getMessage());
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try{
                oi.close();
                fi.close();
                System.out.println("ekleisa");
            }catch(IOException ex) {
                System.err.println("An IOException was caught: " + ex.getMessage());
            }
        }
        List<Mathima> updateMathimataForProf = new ArrayList<>();
        for (int i : selectedIx){
            String math = updateProfMathimata.getModel().getElementAt(i);
            for (Mathima mathima : mathimata){
                if (math.equals(mathima.getOnomaMathimatos())){
                    updateMathimataForProf.add(mathima);
                }
            }            
        }
        admin.updateProf(updateProfUsername.getText(), updateProfPassword.getText(),updateProfMail.getText(),updateProfMail.getText(),
                         updateProfTilefono.getText(), updateProfTmima.getText(),updateProfEidikothta.getText(), updateMathimataForProf);
    }//GEN-LAST:event_updateProfButtonActionPerformed

    private void deleteProfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProfButtonActionPerformed
        admin.deleteProf();
    }//GEN-LAST:event_deleteProfButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        getContentPane().add(searchProfPage);
        getContentPane().repaint();
        getContentPane().revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void clearLoginFields(){
        passwordLogin.setText("");
        usernameLogin.setText("");
    }
    public void goToHomePage(){
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        getContentPane().add(jPanel1);
        getContentPane().repaint();
        getContentPane().revalidate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }
    Admin admin;
    Foititis std;
    Kathigitis prof;
    Mathima math;
    FileOutputStream f = null;
    ObjectOutputStream o = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPage;
    private javax.swing.JPanel FoiththsPage;
    private javax.swing.JPanel KathigitisPage;
    private javax.swing.JButton addMath;
    private javax.swing.JButton addProf;
    private javax.swing.JButton addStd;
    private javax.swing.JButton adminLogoutButton;
    private javax.swing.JButton deleteMathButton;
    private javax.swing.JToggleButton deleteProfButton;
    private javax.swing.JToggleButton deleteStdButton;
    private javax.swing.JButton foiththsLogoutButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kathigitisLogoutButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField mathDM;
    private javax.swing.JTextField mathEksamino;
    private javax.swing.JTextField mathKodikos;
    private javax.swing.JButton mathNewSubmit;
    private javax.swing.JTextField mathOnoma;
    private javax.swing.JTextField mathTmhma;
    private javax.swing.JTextField mathTypos;
    private javax.swing.JPanel newMathPage;
    private javax.swing.JPanel newProfPage;
    private javax.swing.JPanel newStdPage;
    private javax.swing.JPasswordField passwordLogin;
    private javax.swing.JTextField profIdikotita;
    private javax.swing.JTextField profMail;
    private javax.swing.JList<String> profMathimata;
    private javax.swing.JButton profNewSubmit;
    private javax.swing.JTextField profOnomateponimo;
    private javax.swing.JTextField profPassword;
    private javax.swing.JTextField profTilefono;
    private javax.swing.JTextField profTmima;
    private javax.swing.JTextField profUsername;
    private javax.swing.JButton searchMathButton;
    private javax.swing.JTextField searchMathKodikos;
    private javax.swing.JPanel searchMathPage;
    private javax.swing.JButton searchProfButton;
    private javax.swing.JPanel searchProfPage;
    private javax.swing.JTextField searchProfUsername;
    private javax.swing.JButton searchStdButton;
    private javax.swing.JPanel searchStdPage;
    private javax.swing.JTextField searchStdUsername;
    private javax.swing.JTextField stdAM;
    private javax.swing.JTextField stdDieythinsi;
    private javax.swing.JTextField stdEksamino;
    private javax.swing.JTextField stdMail;
    private javax.swing.JButton stdNewSubmit;
    private javax.swing.JTextField stdOnomaEponymo;
    private javax.swing.JTextField stdPassword;
    private javax.swing.JTextField stdThlefwno;
    private javax.swing.JTextField stdTmhma;
    private javax.swing.JTextField stdUsername;
    private javax.swing.JToggleButton updateMathButton;
    private javax.swing.JTextField updateMathDM;
    private javax.swing.JTextField updateMathExamino;
    private javax.swing.JTextField updateMathKodikos;
    private javax.swing.JTextField updateMathOnoma;
    private javax.swing.JPanel updateMathPage;
    private javax.swing.JTextField updateMathTmima;
    private javax.swing.JTextField updateMathTupos;
    private javax.swing.JToggleButton updateProfButton;
    private javax.swing.JTextField updateProfEidikothta;
    private javax.swing.JTextField updateProfMail;
    private javax.swing.JList<String> updateProfMathimata;
    private javax.swing.JTextField updateProfOnomatep;
    private javax.swing.JPanel updateProfPage;
    private javax.swing.JTextField updateProfPassword;
    private javax.swing.JTextField updateProfTilefono;
    private javax.swing.JTextField updateProfTmima;
    private javax.swing.JTextField updateProfUsername;
    private javax.swing.JTextField updateStdAM;
    private javax.swing.JToggleButton updateStdButton;
    private javax.swing.JTextField updateStdDieuthinsi;
    private javax.swing.JTextField updateStdExamino;
    private javax.swing.JTextField updateStdMail;
    private javax.swing.JTextField updateStdOnomatep;
    private javax.swing.JPanel updateStdPage;
    private javax.swing.JTextField updateStdPassword;
    private javax.swing.JTextField updateStdTilefono;
    private javax.swing.JTextField updateStdTmima;
    private javax.swing.JTextField updateStdUsername;
    private javax.swing.JTextField usernameLogin;
    // End of variables declaration//GEN-END:variables
}
