
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author stini
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        AdminPage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adminLogoutButton = new javax.swing.JButton();
        addProf = new javax.swing.JButton();
        addStd = new javax.swing.JButton();
        FoiththsPage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        foiththsLogoutButton = new javax.swing.JButton();
        KathigitisPage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kathigitisLogoutButton = new javax.swing.JButton();
        newStdPage = new javax.swing.JPanel();
        stdUsername = new javax.swing.JTextField();
        stdPassword = new javax.swing.JTextField();
        stdMail = new javax.swing.JTextField();
        stdOnomaEponymo = new javax.swing.JTextField();
        stdAM = new javax.swing.JTextField();
        stdTmhma = new javax.swing.JTextField();
        stdEksamino = new javax.swing.JTextField();
        stdDieythinsi = new javax.swing.JTextField();
        stdThlefwno = new javax.swing.JTextField();
        stdNewSubmit = new javax.swing.JButton();
        newProfPage = new javax.swing.JPanel();
        profOnomateponimo = new javax.swing.JTextField();
        profMail = new javax.swing.JTextField();
        profPassword = new javax.swing.JTextField();
        profUsername = new javax.swing.JTextField();
        profIdikotita = new javax.swing.JTextField();
        profTilefono = new javax.swing.JTextField();
        profTmima = new javax.swing.JTextField();
        profNewSubmit = new javax.swing.JButton();
        MathimaPage = new javax.swing.JPanel();
        onomaMathimatos = new javax.swing.JTextField();
        eksamino = new javax.swing.JTextField();
        eidosEksaminou = new javax.swing.JTextField();
        kodikosMathimatos = new javax.swing.JTextField();
        kateuthinsi = new javax.swing.JTextField();
        submitLesson = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jPasswordField1)))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        jLabel1.setText("Admin Page");

        adminLogoutButton.setText("LogOut");
        adminLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLogoutButtonActionPerformed(evt);
            }
        });

        addProf.setText("Add Professor");
        addProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProfActionPerformed(evt);
            }
        });

        addStd.setText("Add Student");
        addStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminPageLayout = new javax.swing.GroupLayout(AdminPage);
        AdminPage.setLayout(AdminPageLayout);
        AdminPageLayout.setHorizontalGroup(
            AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPageLayout.createSequentialGroup()
                .addGroup(AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPageLayout.createSequentialGroup()
                        .addContainerGap(519, Short.MAX_VALUE)
                        .addComponent(adminLogoutButton))
                    .addGroup(AdminPageLayout.createSequentialGroup()
                        .addGroup(AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addStd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AdminPageLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1))
                                .addGroup(AdminPageLayout.createSequentialGroup()
                                    .addGap(136, 136, 136)
                                    .addComponent(addProf))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AdminPageLayout.setVerticalGroup(
            AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(addProf)
                .addGap(28, 28, 28)
                .addComponent(addStd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                .addComponent(adminLogoutButton)
                .addContainerGap())
        );

        getContentPane().add(AdminPage, "card3");

        jLabel2.setText("Φοιτητής ");

        foiththsLogoutButton.setText("LogOut");
        foiththsLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foiththsLogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FoiththsPageLayout = new javax.swing.GroupLayout(FoiththsPage);
        FoiththsPage.setLayout(FoiththsPageLayout);
        FoiththsPageLayout.setHorizontalGroup(
            FoiththsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FoiththsPageLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel2)
                .addContainerGap(394, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FoiththsPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(foiththsLogoutButton)
                .addContainerGap())
        );
        FoiththsPageLayout.setVerticalGroup(
            FoiththsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FoiththsPageLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 354, Short.MAX_VALUE)
                .addComponent(foiththsLogoutButton)
                .addContainerGap())
        );

        getContentPane().add(FoiththsPage, "card4");

        jLabel3.setText("Καθηγητής");

        kathigitisLogoutButton.setText("LogOut");
        kathigitisLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kathigitisLogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KathigitisPageLayout = new javax.swing.GroupLayout(KathigitisPage);
        KathigitisPage.setLayout(KathigitisPageLayout);
        KathigitisPageLayout.setHorizontalGroup(
            KathigitisPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KathigitisPageLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel3)
                .addContainerGap(406, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KathigitisPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kathigitisLogoutButton)
                .addContainerGap())
        );
        KathigitisPageLayout.setVerticalGroup(
            KathigitisPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KathigitisPageLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(kathigitisLogoutButton)
                .addContainerGap())
        );

        getContentPane().add(KathigitisPage, "card5");

        stdUsername.setText("jTextField2");

        stdPassword.setText("jTextField3");

        stdMail.setText("jTextField4");

        stdOnomaEponymo.setText("jTextField4");

        stdAM.setText("jTextField4");

        stdTmhma.setText("jTextField4");

        stdEksamino.setText("jTextField4");

        stdDieythinsi.setText("jTextField4");

        stdThlefwno.setText("jTextField4");

        stdNewSubmit.setText("Submit");
        stdNewSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdNewSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newStdPageLayout = new javax.swing.GroupLayout(newStdPage);
        newStdPage.setLayout(newStdPageLayout);
        newStdPageLayout.setHorizontalGroup(
            newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStdPageLayout.createSequentialGroup()
                .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(newStdPageLayout.createSequentialGroup()
                        .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newStdPageLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(stdUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStdPageLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stdAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdEksamino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdThlefwno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(258, 258, 258)))
                        .addComponent(stdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newStdPageLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(stdMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stdOnomaEponymo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newStdPageLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stdDieythinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdTmhma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStdPageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(stdNewSubmit)
                .addGap(34, 34, 34))
        );
        newStdPageLayout.setVerticalGroup(
            newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newStdPageLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdOnomaEponymo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(stdThlefwno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdTmhma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(newStdPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newStdPageLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(stdDieythinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newStdPageLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(stdEksamino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stdNewSubmit)
                .addGap(36, 36, 36))
        );

        getContentPane().add(newStdPage, "card6");

        profOnomateponimo.setText("jTextField4");

        profMail.setText("jTextField4");

        profPassword.setText("jTextField3");

        profUsername.setText("jTextField2");

        profIdikotita.setText("jTextField4");

        profTilefono.setText("jTextField4");

        profTmima.setText("jTextField4");

        profNewSubmit.setText("Submit");
        profNewSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profNewSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newProfPageLayout = new javax.swing.GroupLayout(newProfPage);
        newProfPage.setLayout(newProfPageLayout);
        newProfPageLayout.setHorizontalGroup(
            newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newProfPageLayout.createSequentialGroup()
                .addContainerGap(509, Short.MAX_VALUE)
                .addComponent(profNewSubmit)
                .addGap(18, 18, 18))
            .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newProfPageLayout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(newProfPageLayout.createSequentialGroup()
                            .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(newProfPageLayout.createSequentialGroup()
                                    .addComponent(profUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newProfPageLayout.createSequentialGroup()
                                    .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(profTilefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(profTmima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(258, 258, 258)))
                            .addComponent(profPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(newProfPageLayout.createSequentialGroup()
                            .addComponent(profMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profOnomateponimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(newProfPageLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profIdikotita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(108, 108, 108)))
        );
        newProfPageLayout.setVerticalGroup(
            newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newProfPageLayout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addComponent(profNewSubmit)
                .addContainerGap())
            .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newProfPageLayout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(profUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(profMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profOnomateponimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(178, 178, 178)
                    .addGroup(newProfPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(profIdikotita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profTilefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(60, 60, 60)
                    .addComponent(profTmima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(newProfPage, "card7");

        onomaMathimatos.setText("Onoma Mathimatos");
        onomaMathimatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onomaMathimatosActionPerformed(evt);
            }
        });

        eksamino.setText("eksamino");
        eksamino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eksaminoActionPerformed(evt);
            }
        });

        eidosEksaminou.setText("eidosEksaminou");
        eidosEksaminou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidosEksaminouActionPerformed(evt);
            }
        });

        kodikosMathimatos.setText("kodikosMathimatos");
        kodikosMathimatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodikosMathimatosActionPerformed(evt);
            }
        });

        kateuthinsi.setText("kateuthinsi");
        kateuthinsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kateuthinsiActionPerformed(evt);
            }
        });

        submitLesson.setText("Submit");
        submitLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitLessonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MathimaPageLayout = new javax.swing.GroupLayout(MathimaPage);
        MathimaPage.setLayout(MathimaPageLayout);
        MathimaPageLayout.setHorizontalGroup(
            MathimaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MathimaPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MathimaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(onomaMathimatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eksamino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eidosEksaminou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodikosMathimatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kateuthinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(484, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MathimaPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitLesson)
                .addGap(39, 39, 39))
        );
        MathimaPageLayout.setVerticalGroup(
            MathimaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MathimaPageLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(onomaMathimatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eksamino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eidosEksaminou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kodikosMathimatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kateuthinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                .addComponent(submitLesson)
                .addGap(27, 27, 27))
        );

        getContentPane().add(MathimaPage, "card8");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        Account admin = new Admin("it174890", "633818", "it174890@it.teithe.gr", "Γιώργος Στίνης", "2310574479");
//        Account kathigitis = new Kathigitis("daddy", "keftedaki", "dad@it.teithe.gr", "SallaDaddy", "6948855476", "Μαθηματικός", "Μηχανικών Πληροφορικής");
//        Account foithths = new Foititis("ego", "555", "ego@gmail.com", "ego memena", "", 174891, "Διοικηση", 5, "Λαχανά 22");
//        FileOutputStream f;
//        ObjectOutputStream o;
        FileInputStream fi=null;
        ObjectInputStream oi=null;
        try {
//            f = new FileOutputStream(new File("myAccounts.txt"));
//            o = new ObjectOutputStream(f);
//            o.writeObject(admin);
//            o.writeObject(kathigitis);
//            o.writeObject(foithths);
//            o.close();
//            f.close();
            fi = new FileInputStream(new File("myAccounts.txt"));
            oi = new ObjectInputStream(fi);
            Account a1;
            String usernameTextfield = jTextField1.getText();
            char[] passwordTextfield = jPasswordField1.getPassword();
            clearLoginFields();
            while (true){
                try{
                    a1=(Account)oi.readObject();
                    if(a1 instanceof Admin){
                        admin = (Admin)a1;
                    }
                    char[] passwordArray = a1.getPassword().toCharArray();
                    if(Arrays.equals(passwordTextfield, passwordArray) && a1.getUsername().equals(usernameTextfield)){
                        getContentPane().removeAll();
                        getContentPane().repaint();
                        getContentPane().revalidate();
                        switch (a1.getIdiotita()) {
                            case "Administrator":
                                getContentPane().add(AdminPage);
                                break;
                            case "Professor":
                                getContentPane().add(KathigitisPage);
                                break;
                            case "Student":
                                getContentPane().add(FoiththsPage);
                                break;
                            default:
                                break;
                        }
                        getContentPane().repaint();
                        getContentPane().revalidate();
                        break;
                    }
                }catch (EOFException ex1) {
                    break; //EOF reached.
                }catch (IOException ex2) {
                    System.err.println("An IOException was caught: " + ex2.getMessage());
                }
            }
        }catch (IOException ex) {
            System.err.println("An IOException was caught: " + ex.getMessage());
        }catch (ClassNotFoundException ex) {
            System.out.println("Geia");
        }finally{
            try{
                oi.close();
                fi.close();
                System.out.println("ekleisa");
            }catch(IOException ex) {
                System.err.println("An IOException was caught: " + ex.getMessage());
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void kathigitisLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kathigitisLogoutButtonActionPerformed
        goToHomePage();
    }//GEN-LAST:event_kathigitisLogoutButtonActionPerformed

    private void foiththsLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foiththsLogoutButtonActionPerformed
        goToHomePage();
    }//GEN-LAST:event_foiththsLogoutButtonActionPerformed

    private void adminLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLogoutButtonActionPerformed
        goToHomePage();
    }//GEN-LAST:event_adminLogoutButtonActionPerformed

    private void addStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStdActionPerformed
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        getContentPane().add(newStdPage);
        getContentPane().repaint();
        getContentPane().revalidate();
    }//GEN-LAST:event_addStdActionPerformed

    private void stdNewSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdNewSubmitActionPerformed
        String usernameStd = stdUsername.getText();
        String passStd = stdPassword.getText();
        String mailStd = stdMail.getText();
        String onomateponumoStd = stdOnomaEponymo.getText();
        String thlefwnoStd = stdThlefwno.getText();
        int AMstd = Integer.parseInt(stdAM.getText());
        String tmhmaStd = stdTmhma.getText();
        int eksaminoStd = Integer.parseInt(stdEksamino.getText());
        String dieythinsiStd = stdDieythinsi.getText();
        admin.createStd(usernameStd, passStd, mailStd, onomateponumoStd, thlefwnoStd, AMstd, tmhmaStd, eksaminoStd, dieythinsiStd);
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        getContentPane().add(AdminPage);
        getContentPane().repaint();
        getContentPane().revalidate();
    }//GEN-LAST:event_stdNewSubmitActionPerformed

    private void profNewSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profNewSubmitActionPerformed
        String usernameProf = profUsername.getText();
        String passWordProf = profPassword.getText();
        String mailProf = profMail.getText();
        String onomateponumoProf = profOnomateponimo.getText();
        String thlefwnoProf = profTilefono.getText();
        String idikotitaProf = profIdikotita.getText();
        String tmimaProf = profTmima.getText();
        admin.createProf(usernameProf, passWordProf, mailProf, onomateponumoProf, thlefwnoProf, idikotitaProf, tmimaProf);
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        getContentPane().add(AdminPage);
        getContentPane().repaint();
        getContentPane().revalidate();
    }//GEN-LAST:event_profNewSubmitActionPerformed

    private void addProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProfActionPerformed
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        getContentPane().add(newProfPage);
        getContentPane().repaint();
        getContentPane().revalidate();
    }//GEN-LAST:event_addProfActionPerformed

    private void onomaMathimatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onomaMathimatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onomaMathimatosActionPerformed

    private void eksaminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eksaminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eksaminoActionPerformed

    private void eidosEksaminouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidosEksaminouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eidosEksaminouActionPerformed

    private void kodikosMathimatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodikosMathimatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodikosMathimatosActionPerformed

    private void kateuthinsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kateuthinsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kateuthinsiActionPerformed

    private void submitLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitLessonActionPerformed
        // TODO add your handling code here:
        String onomaM = onomaMathimatos.getText();
        int eks = Integer.parseInt(eksamino.getText());
        String eidos = eidosEksaminou.getText();
        int kodikos = Integer.parseInt(kodikosMathimatos.getText());
        String kat = kateuthinsi.getText();
        admin.createLesson(onomaM, eks, eidos, kodikos, kat);
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        getContentPane().add(AdminPage);
        getContentPane().repaint();
        getContentPane().revalidate();
    }//GEN-LAST:event_submitLessonActionPerformed
    public void clearLoginFields(){
        jPasswordField1.setText("");
        jTextField1.setText("");
    }
    public void goToHomePage(){
        getContentPane().removeAll();
        getContentPane().repaint();
        getContentPane().revalidate();
        getContentPane().add(jPanel1);
        getContentPane().repaint();
        getContentPane().revalidate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    Admin admin;
    Foititis std;
    Kathigitis prof;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPage;
    private javax.swing.JPanel FoiththsPage;
    private javax.swing.JPanel KathigitisPage;
    private javax.swing.JPanel MathimaPage;
    private javax.swing.JButton addProf;
    private javax.swing.JButton addStd;
    private javax.swing.JButton adminLogoutButton;
    private javax.swing.JTextField eidosEksaminou;
    private javax.swing.JTextField eksamino;
    private javax.swing.JButton foiththsLogoutButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField kateuthinsi;
    private javax.swing.JButton kathigitisLogoutButton;
    private javax.swing.JTextField kodikosMathimatos;
    private javax.swing.JPanel newProfPage;
    private javax.swing.JPanel newStdPage;
    private javax.swing.JTextField onomaMathimatos;
    private javax.swing.JTextField profIdikotita;
    private javax.swing.JTextField profMail;
    private javax.swing.JButton profNewSubmit;
    private javax.swing.JTextField profOnomateponimo;
    private javax.swing.JTextField profPassword;
    private javax.swing.JTextField profTilefono;
    private javax.swing.JTextField profTmima;
    private javax.swing.JTextField profUsername;
    private javax.swing.JTextField stdAM;
    private javax.swing.JTextField stdDieythinsi;
    private javax.swing.JTextField stdEksamino;
    private javax.swing.JTextField stdMail;
    private javax.swing.JButton stdNewSubmit;
    private javax.swing.JTextField stdOnomaEponymo;
    private javax.swing.JTextField stdPassword;
    private javax.swing.JTextField stdThlefwno;
    private javax.swing.JTextField stdTmhma;
    private javax.swing.JTextField stdUsername;
    private javax.swing.JButton submitLesson;
    // End of variables declaration//GEN-END:variables
}
